{
 "title": "Ethereum 2",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Validator Earnings",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Nimbus Client Status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Total Validator Balance (ETH)",
   "type": "stat",
   "description": "Sum of all validator balances.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "attached_validator_balance_total{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}/1000000000",
     "legendFormat": "vbal"
    }
   ]
  },
  {
   "title": "Total Earnings (ETH)",
   "type": "stat",
   "description": "Total ETH return on the initial effective stake of active local validators.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"})/1000000000-(count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)*32)"
    }
   ]
  },
  {
   "title": "Total Return",
   "type": "singlestat",
   "description": "Total percentage return on the initial effective stake of active local validators. Excess deposits will be reflected as earnings.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"})/1000000000-(count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)*32))/(count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)*32)  "
    }
   ]
  },
  {
   "title": "Validator Balances",
   "type": "table-old",
   "description": "Validator balances by public key. ",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}/1000000000), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{8}).*\") ",
     "legendFormat": "balance"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey_short\", \"(.{8}).*\") "
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Number of beacon nodes to which this node is connected.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "libp2p_peers{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}"
    }
   ]
  },
  {
   "title": "Beacon Uptime",
   "type": "singlestat",
   "description": "The length of time the beacon chain process has been running",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon-validator.nimbus-prater.dappnode:8008\"})/3600"
    }
   ]
  },
  {
   "title": "Total Validator Count",
   "type": "stat",
   "description": "Count of active validators.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_active_validators{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} ",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((finalization_delay{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}-2)/100))),0)"
    }
   ]
  },
  {
   "title": "Total Validator Balance (USD)",
   "type": "stat",
   "description": "Sum of all validator balances multiplied by the price of ETH in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ethusd ", "legendFormat": "ethusd" },
    {
     "expr": "attached_validator_balance_total{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}/1000000000",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Total Earnings (USD)",
   "type": "stat",
   "description": "Total earnings in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"})/1000000000-(count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)*32)",
     "legendFormat": "total_balance"
    },
    { "expr": "ethusd", "legendFormat": "ethusd" }
   ]
  },
  {
   "title": "ETH Price (USD)",
   "type": "stat",
   "description": "Price of ETH in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ethusd", "legendFormat": "ethusd" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "libp2p_peers{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Justified, and finalized epochs. In this order, these two values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"beacon-validator.nimbus-prater.dappnode:8008\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Earnings Rates",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "beacon_pending_deposits{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "beacon_active_validators{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Hourly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "ETH",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"})/1000000000 - sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 1h != 0)/1000000000 - (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)) + (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 1h > 16))"
    }
   ]
  },
  {
   "title": "Daily Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "ETH",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"})/1000000000 - sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 1d != 0)/1000000000 - (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)) + (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 1d > 16))"
    }
   ]
  },
  {
   "title": "Weekly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "ETH",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"})/1000000000 - sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 7d != 0)/1000000000 - (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)) + (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 7d > 16))"
    }
   ]
  },
  {
   "title": "Monthly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "format": "ETH",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"})/1000000000 - sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 30d != 0)/1000000000 - (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)) + (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 30d > 16))"
    }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "stat",
   "description": "Total number of block proposals and attestations made by local validators since the last restart of the beacon chain.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_blocks_proposed_total{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "proposals"
    },
    {
     "expr": "beacon_attestations_sent_total{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "attestations"
    }
   ]
  },
  {
   "title": "Slashings Received",
   "type": "stat",
   "description": "Number of proposer and attester slashings received by the local beacon chain since the last restart of the beacon chain.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_proposer_slashings_received_total{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "proposer"
    },
    {
     "expr": "beacon_attester_slashings_received_total{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "attester"
    }
   ]
  },
  {
   "title": "Hourly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}) - sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 1h != 0) - (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)) + (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 1h > 16)))/(32 * avg_over_time(count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)[1h:])))/1000000000 * 365 * 24",
     "legendFormat": "annualized hourly return"
    }
   ]
  },
  {
   "title": "Daily Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}) - sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 1d != 0) - (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)) + (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 1d > 16)))/(32 * avg_over_time(count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)[1d:])))/1000000000 * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Weekly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}) - sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 7d != 0) - (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)) + (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 7d > 16)))/(32 * avg_over_time(count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)[7d:])))/1000000000 * (365/7)",
     "legendFormat": "annualized weekly return"
    }
   ]
  },
  {
   "title": "Monthly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}) - sum(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 30d != 0) - (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)) + (32 * count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} offset 30d > 16)))/(32 * avg_over_time(count(attached_validator_balance{job=\"beacon-validator.nimbus-prater.dappnode:8008\"} > 16)[30d:])))/1000000000 * (365/30)",
     "legendFormat": "annualized monthly return"
    }
   ]
  },
  {
   "title": "Voluntary Exits Received",
   "type": "stat",
   "description": "Number of voluntary exits received by the local beacon chain since the last restart of the beacon chain.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_voluntary_exits_received_total{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "voluntary exits received"
    }
   ]
  },
  {
   "title": "Failed web3 Requests",
   "type": "stat",
   "description": "Number of failed web3 requests since the last restart of the beacon chain.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "failed_web3_requests_total{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "failed requests"
    }
   ]
  },
  {
   "title": "Pending Validator Queue",
   "type": "stat",
   "description": "Current number of pending validators",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_pending_deposits{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Pending Queue Length",
   "type": "stat",
   "description": "Estimated length of time until all pending validators have cleared the queue.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((beacon_pending_deposits{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}/4)*6.4)",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Server",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "graph",
   "description": "Beacon chain and validator memory usage on the server.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_occupied_bytes{job=\"beacon-validator.nimbus-prater.dappnode:8008\"}",
     "legendFormat": "beacon memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Processor usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"system\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"user\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"nice\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"iowait\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"steal\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"idle\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"irq\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"softirq\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"guest\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Network transmission (tx) and reception (rx) rates",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter\",device='enp1s0'}[5m])*8 or irate(node_network_transmit_bytes{job=\"node_exporter\",device='enp1s0'}[5m])*8 or irate(node_network_transmit_bytes_total{job=\"node_exporter\",device='eno1'}[5m])*8 or irate(node_network_transmit_bytes{job=\"node_exporter\",device='eno1'}[5m])*8",
     "legendFormat": "tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter\",device='enp1s0'}[5m])*8 or irate(node_network_receive_bytes{job=\"node_exporter\",device='enp1s0'}[5m])*8 or irate(node_network_receive_bytes_total{job=\"node_exporter\",device='eno1'}[5m])*8 or irate(node_network_receive_bytes{job=\"node_exporter\",device='eno1'}[5m])*8",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node_exporter\"})-sum(node_filesystem_avail_bytes{job=\"node_exporter\"}))/sum(node_filesystem_size_bytes{job=\"node_exporter\"})",
     "legendFormat": "disk usage"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "graph",
   "description": "Memory usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{job=\"node_exporter\"} - node_memory_MemFree_bytes{job=\"node_exporter\"} - node_memory_Buffers_bytes{job=\"node_exporter\"} - node_memory_Cached_bytes{job=\"node_exporter\"} - node_memory_SwapCached_bytes{job=\"node_exporter\"} - node_memory_Slab_bytes{job=\"node_exporter\"} - node_memory_PageTables_bytes{job=\"node_exporter\"} - node_memory_VmallocUsed_bytes{job=\"node_exporter\"} ) or ( node_memory_MemTotal{job=\"node_exporter\"} - node_memory_MemFree{job=\"node_exporter\"} - node_memory_Buffers{job=\"node_exporter\"} - node_memory_Cached{job=\"node_exporter\"} - node_memory_SwapCached{job=\"node_exporter\"} - node_memory_Slab{job=\"node_exporter\"} - node_memory_PageTables{job=\"node_exporter\"} - node_memory_VmallocUsed{job=\"node_exporter\"} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node_exporter\"} or node_memory_Buffers{job=\"node_exporter\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter\"} or node_memory_Cached{job=\"node_exporter\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\"} or node_memory_MemFree{job=\"node_exporter\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"node_exporter\"} or node_memory_Slab{job=\"node_exporter\"}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\",job=\"node_exporter\",sensor=\"temp1\"}",
     "legendFormat": "cpu temp"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"ping_google\"}",
     "legendFormat": "google"
    },
    {
     "expr": "probe_duration_seconds{job=\"ping_cloudflare\"}",
     "legendFormat": "cloudflare"
    }
   ]
  }
 ]
}